name: CI

on: [push]

jobs:
  test:
    name: Run jest unit tests and linter
    runs-on: [windows-latest]
    steps:
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test:unit
      - name: Run linter
        run: npm run lint
