name: CI

on: [push]

jobs:
  test:
    name: Run jest unit tests and linter
    runs-on: [windows-latest]
    
    strategy:
      matrix:
        node-version: [10.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test:unit
      - name: Run linter
        run: npm run lint
